# Generated by Django 4.1.5 on 2023-07-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comite', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=250)),
                ('detalle', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('comite', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main.comites')),
            ],
        ),
    ]
